---
name: Lint Flow

on:
  - push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
        with:
          src: src/
          args: --config pyproject.toml
